[dataset]
# S3 URI of the fMRIprep preprocessed data
preprocessed_uri = "s3://fcp-indi/data/Projects/ADHD200/Outputs/fmriprep/fmriprep/"

# S3 URI of the phenotypes data
description_uri = "s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/"

# Root directory
data_dir = "data"

# Downloaded preprocessed images directory
raw_dir = "data/raw"

# Preprocessed data directory
preprocessed_dir = "data/processed"

# Phenotypes directory
phenotypes_dir = "data/phenotypes"

# Label distribution plot directory
plot_dir = "data/plots"

[feature]

rfe_n_features = 90
site_to_train = "NYU" # Available sites: NEURO, NYU, OHSU, 
fc_variant = "fc90" # Options: "fc90" (90 ROIs, unsegmented) | "full" (full AAL, segmented)
regions_to_remove = [115] # Regions to remove from the FC data

[model] # (Not used in the AECLS cross-validation setup)
# Common model configuration
input_dim = 90
dropout = 0.1

[training] # (Not used in the AECLS cross-validation setup)
batch_size = 4
learning_rate = 0.0001
num_epochs = 100
weight_decay = 0.0001