[project]
name = "adhd-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.73",
    "jupyter>=1.1.1",
    "nilearn>=0.12.1",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
]

[tool.basedpyright]
typeCheckingMode = "basic"
exclude = ["data/**"]
